### ISSUE TITLE
Dictionary of labels

### ISSUE THREAD

**Issue by argideritzalpea** [OnlpLab/Modality-Corpus#1]
It would be really great if there was a document / file that constituted a dictionary of the labels used in both the course and fine-grained datasets, their corresponding meanings, and examples of them in the dataset.

Thanks for your work on this important issue.

**Comment by ValentinaPy** [comment]
Hi, 
Thank you for the interest in the corpus! @shovalsa agreed to create such a file. She will upload it soon!

**Comment by shovalsa** [comment]
Hi @argideritzalpea ,
I've added a json file that represents the taxonomy, with descriptions and examples from the paper. I hope you'll find it useful.
https://github.com/OnlpLab/Modality-Corpus/blob/main/taxonomy.json

**Comment by argideritzalpea** [comment]
@ValentinaPy @shovalsa  Thank you for adding this!

**Comment by argideritzalpea** [comment]
@ValentinaPy @shovalsa Also, I was hoping to try to train this according to the annotated corpus that you have provided, but first I'd like to verify whether or not a trained model is released and available to download to use with the main Modality repo codebase?

**Comment by ValentinaPy** [comment]
Hi, yes, we just added instructions to the README of the modality code base (https://github.com/OnlpLab/Modality) on how to make predictions with already trained models (for now we provided 3 different types of models for the fine-grained layer). Let us know if you need others. Hope that was helpful!
